# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  external_labels:
    monitor: 'Kafka'

scrape_configs:
  - job_name: 'kafka-broker'
    scrape_interval: 10s
    static_configs:
      - targets: ['kafka:29101']
        labels:
          service: kafka-broker

