# https://github.com/bitnami/bitnami-docker-kafka/issues/265
version: '3'
services:
  kafka:
    image: bitnami/kafka:3.3.1
    container_name: tantalo-kafka
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://${EXPOSED_URL}:9094
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_NUM_PARTITIONS=3 # Allows up to 3 concurrent workers
      - EXTRA_ARGS= -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.17.0.jar=29101:/usr/share/jmx_exporter/kafka-broker.yaml
    ports:
      - "0.0.0.0:9094:9094"
    volumes:
      - ./jmx-exporter:/usr/share/jmx_exporter/
    #    - kafka-jmx-volume:/jmx-exporter
    restart: always

  prometheus:
    container_name: tantalo-prometheus
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus/:/etc/prometheus/
    #  - prometheus-volume:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    depends_on:
      - kafka
    restart: always

  influxdb:
    container_name: tantalo-influxdb
    image: influxdb:2.6.0
    ports:
      - "18086:8086"
    # depends_on:
    #   - kafka
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin1234
      - DOCKER_INFLUXDB_INIT_ORG=fitness
      - DOCKER_INFLUXDB_INIT_BUCKET=misure
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=2abdb6a7-ea6e-4044-a051-5f1a99fed42c
    volumes:
      - ./influxdb/scripts:/docker-entrypoint-initdb.d
    #      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
    restart: always

  kafka-ui:
    container_name: tantalo-kafka-ui
    image: provectuslabs/kafka-ui:v0.5.0
    ports:
      - "18080:8080"
    depends_on:
      - kafka
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    restart: always

  grafana:
    container_name: tantalo-grafana
    image: grafana/grafana:9.3.2
    depends_on:
      - prometheus
    volumes:
      # - grafana-volume:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=admin1234"
      - "GF_USERS_ALLOW_SIGN_UP=false"
    ports:
      - "13000:3000"
    restart: always




